github: Ronin15 # Replace with your GitHub username to enable GitHub Sponsors (if applicable)
patreon: HammerForgedGames
#open_collective: [your-open-collective-slug]
#ko_fi: [your-ko-fi-username]
#buymeacoffee: [your-buymeacoffee-username]
#custom: ["https://your-custom-url.example"]
