agent:
  agent_id: null
  hostname: null
  collection_interval_ms: 5000
  max_events_per_batch: 1000
  max_memory_usage_mb: 512
collectors:
  process_monitor:
    enabled: true
    scan_interval_ms: 1000
    track_child_processes: true
    collect_command_line: true
    collect_environment: false
  file_monitor:
    enabled: true
    watched_paths:
    - /
    - C:\
    ignored_extensions:
    - .tmp
    - .log
    - .cache
    - .lock
    - .swp
    - .pid
    max_file_size_mb: 50  # Balanced size for security coverage and performance
    calculate_hashes: true
  network_monitor:
    enabled: true
    monitor_connections: true
    monitor_dns: true
    capture_packets: false
    max_packet_size: 1500
  registry_monitor:
    enabled: false
    watched_keys:
    - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    - HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
detectors:
  behavioral:
    enabled: true
    scan_interval_ms: 2000
    alert_threshold: 0.4  # Lower to catch more suspicious behavior
    prevention_threshold: 0.8  # Keep prevention threshold high to avoid false positives
    track_api_calls: true
    monitor_memory_operations: true
    monitor_thread_operations: true
    cross_platform_detection: true
    system_process_contexts:
      # Linux processes
      Xwayland:
        expected_paths:
          - "/usr/bin/Xwayland"
        max_instances: 1
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 4.0
      pipewire:
        expected_paths:
          - "/usr/bin/pipewire"
        max_instances: 5
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 4.0
      wireplumber:
        expected_paths:
          - "/usr/bin/wireplumber"
        max_instances: 2
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 4.0
      gnome-shell:
        expected_paths:
          - "/usr/bin/gnome-shell"
          - "/usr/lib/gnome-shell"
        max_instances: 1
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 4.0
      gnome-keyring-daemon:
        expected_paths:
          - "/usr/bin/gnome-keyring-daemon"
        max_instances: 1
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 4.0
      gnome-system-monitor:
        expected_paths:
          - "/usr/bin/gnome-system-monitor"
        max_instances: 1
        baseline_risk_reduction: 0.8
        elevated_risk_multiplier: 3.0
      gjs-console:
        expected_paths:
          - "/usr/bin/gjs-console"
          - "/usr/bin/gjs"
        max_instances: 10
        baseline_risk_reduction: 0.8
        elevated_risk_multiplier: 3.0
      systemd:
        expected_paths:
          - "/sbin/"
          - "/bin/"
          - "/usr/sbin/"
        max_instances: 1
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 5.0
      
      # Windows processes
      svchost:
        expected_paths:
          - "C:\\Windows\\System32\\"
          - "C:\\Windows\\SysWOW64\\"
        max_instances: 30
        baseline_risk_reduction: 0.8
        elevated_risk_multiplier: 4.0
      lsass:
        expected_paths:
          - "C:\\Windows\\System32\\"
        max_instances: 1
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 5.0
      csrss:
        expected_paths:
          - "C:\\Windows\\System32\\"
        max_instances: 4
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 5.0
      
      # macOS processes
      mdworker_shared:
        expected_paths:
          - "/System/Library/Frameworks/CoreServices.framework/"
          - "/usr/libexec/"
        max_instances: 20
        baseline_risk_reduction: 0.7
        elevated_risk_multiplier: 2.5
      sharingd:
        expected_paths:
          - "/usr/libexec/"
          - "/System/Library/"
        max_instances: 1
        baseline_risk_reduction: 0.8
        elevated_risk_multiplier: 3.0
      ReportCrash:
        expected_paths:
          - "/System/Library/CoreServices/"
        max_instances: 5
        baseline_risk_reduction: 0.9
        elevated_risk_multiplier: 4.0
    alert_frequency_limits:
      # Linux-specific alerts
      ptrace_injection:
        max_alerts_per_hour: 2
        cooldown_multiplier: 0.2  # Very critical, reduce frequency aggressively
      so_injection:
        max_alerts_per_hour: 2
        cooldown_multiplier: 0.2
      linux_shell_pattern:
        max_alerts_per_hour: 8
        cooldown_multiplier: 0.4
      linux_memory_map:
        max_alerts_per_hour: 5
        cooldown_multiplier: 0.3
      
      # Cross-platform alerts
      suspicious_shell:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.3
      process_injection:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.3
      memory_operation:
        max_alerts_per_hour: 5
        cooldown_multiplier: 0.2
      suspicious_path:
        max_alerts_per_hour: 8
        cooldown_multiplier: 0.6
      
      # Windows-specific alerts
      dll_injection:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.3
      process_hollowing:
        max_alerts_per_hour: 10
        cooldown_multiplier: 0.8
      token_manipulation:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.3
      
      # macOS-specific alerts
      macos_task_port:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.3
      dylib_injection:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.3
      macos_shell:
        max_alerts_per_hour: 5
        cooldown_multiplier: 0.5
    path_context_rules:
      linux_tmp:
        patterns:
          - "/tmp/"
          - "/var/tmp/"
          - "/dev/shm/"
        alert_threshold_multiplier: 2.0
        max_alerts_per_hour: 5
        context_type: SystemTemp
      linux_binary:
        patterns:
          - "/bin/"
          - "/sbin/"
          - "/usr/bin/"
          - "/usr/sbin/"
        alert_threshold_multiplier: 0.5
        max_alerts_per_hour: 5
        context_type: SystemBinary
      browser_cache:
        patterns:
          - "/.cache/mozilla/"
          - "/.cache/google-chrome/"
          - "/.cache/chromium/"
        alert_threshold_multiplier: 2.0
        max_alerts_per_hour: 8
        context_type: BrowserData

      # Windows path contexts
      windows_temp:
        patterns:
          - "C:\\Windows\\Temp\\"
          - "C:\\Users\\*\\AppData\\Local\\Temp\\"
          - "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Temp\\"
        alert_threshold_multiplier: 1.5
        max_alerts_per_hour: 10
        context_type: SystemTemp
      windows_system:
        patterns:
          - "C:\\Windows\\System32\\"
          - "C:\\Windows\\SysWOW64\\"
          - "C:\\Windows\\"
        alert_threshold_multiplier: 0.5
        max_alerts_per_hour: 5
        context_type: SystemBinary
      windows_browser_cache:
        patterns:
          - "C:\\Users\\*\\AppData\\Local\\Google\\Chrome\\User Data\\"
          - "C:\\Users\\*\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\"
          - "C:\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\User Data\\"
        alert_threshold_multiplier: 2.0
        max_alerts_per_hour: 8
        context_type: BrowserData

      # macOS path contexts
      macos_temp:
        patterns:
          - "/private/tmp/"
          - "/private/var/tmp/"
          - "/Library/Caches/"
        alert_threshold_multiplier: 1.5
        max_alerts_per_hour: 10
        context_type: SystemTemp
      macos_system:
        patterns:
          - "/System/Library/"
          - "/usr/libexec/"
          - "/usr/bin/"
          - "/usr/sbin/"
        alert_threshold_multiplier: 0.5
        max_alerts_per_hour: 5
        context_type: SystemBinary
      macos_browser_cache:
        patterns:
          - "/Library/Caches/Mozilla/"
          - "/Library/Caches/Google/Chrome/"
          - "/Library/Application Support/Firefox/"
        alert_threshold_multiplier: 2.0
        max_alerts_per_hour: 8
        context_type: BrowserData
    network_behavior_rules:
      linux_network_monitor:
        process_patterns:
          - "nc"
          - "netcat"
          - "socat"
          - "ncat"
        suspicious_network_threshold: 0.7
        max_network_alerts_per_hour: 5
        whitelisted_ports: [80, 443, 53, 22, 3306]
        behavior_tolerance: Medium
      linux_dns_monitor:
        process_patterns:
          - "dig"
          - "host"
          - "nslookup"
        suspicious_network_threshold: 0.6
        max_network_alerts_per_hour: 10
        whitelisted_ports: [53, 853]
        behavior_tolerance: Low
      linux_file_transfer:
        process_patterns:
          - "scp"
          - "rsync"
          - "sftp"
          - "wget"
          - "curl"
        suspicious_network_threshold: 0.5
        max_network_alerts_per_hour: 15
        whitelisted_ports: [22, 80, 443]
        behavior_tolerance: Medium
    time_based_risk_adjustment:
      business_hours_multiplier: 0.0
      after_hours_multiplier: 0.0
      weekend_multiplier: 0.0
      business_hours_start: 0
      business_hours_end: 0
    process_whitelist:
      enabled: true
      process_names:
        - tokio-runtime-w
        - edr-agent
        - rust_edr_agent
        - systemd
        - systemd-journal
        - systemd-udevd
        - systemd-resolved
        - systemd-timesyncd
        - warp-terminal
        - merge_thread_0
        # Add frequently triggered processes
        - dbus-daemon
        - pulseaudio
        - pipewire-media-session
        - rtkit-daemon
        - gdm-session-worker
        - gvfsd
        - gvfsd-fuse
        - gvfsd-trash
        - tracker-miner-fs
        - colord
        - packagekitd
      # GNOME core processes
        - gnome-shell
        - gnome-session-binary
        - gnome-keyring-daemon
        - gnome-system-monitor
        - gjs-console
        - gjs
        # Display and multimedia processes
        - Xwayland
        - pipewire
        - pipewire-pulse
        - wireplumber
        - module-rt
        - pw-data-loop
        - Xwaylan:disk$0
        # GNOME helper threads
        - gmain
        - gdbus
        - timer
        - pool-spawner
        - JS Helper
        - KMS thread
        - dconf worker
        # GNOME system monitor threads
        - gnome-sy:gdrv0
        - gnome-s:disk$0
        - gnome-:traceq0
        - gnome-shel:sh0
        - gnome-syst:sh0
      process_paths:
        - target/debug/
        - target/release/
        - /lib/systemd/systemd
        - /usr/lib/systemd/systemd
        - /usr/bin/systemctl
        - /opt/warpdotdev/warp-terminal/warp
        # Common system paths
        - /usr/bin/
        - /usr/sbin/
        - /usr/lib/
        - /usr/libexec/
        - /usr/share/
        - /lib/
        - /var/lib/
        # Runtime paths
        - /run/user/
        - /run/systemd/
        - /run/dbus/
        # Display and multimedia paths
        - /usr/bin/Xwayland
        - /usr/bin/pipewire
        - /usr/bin/wireplumber
        # GNOME core paths
        - /usr/bin/gnome-shell
        - /usr/libexec/gnome-session-binary
        - /usr/bin/gnome-keyring-daemon
        - /usr/bin/gnome-system-monitor
        - /usr/bin/gjs
        - /usr/bin/gjs-console
        # GNOME services
        - /usr/libexec/gnome-shell-calendar-server
        - /usr/libexec/at-spi2-registryd
        - /usr/libexec/xdg-desktop-portal-gnome
      command_line_patterns:
        - "systemctl status"
        - "systemctl is-active"
        - "systemctl is-enabled"
        - "journalctl -xe"
        - "journalctl -u"
      parent_process_names:
        - systemd
        - systemd-journal
        - init
        - warp-terminal
        # GNOME parent processes
        - gnome-shell
        - gnome-session-binary
        - gnome-keyring-daemon
        - gnome-system-monitor
        # Display and multimedia parents
        - Xwayland
        - pipewire
        - pipewire-pulse
        - wireplumber
      agent_processes:
        - tokio-runtime-w
        - edr-agent
  dns_anomaly:
    enabled: true
    max_queries_per_minute: 100
    max_queries_per_hour: 1000
    max_unique_domains_per_hour: 500
    entropy_threshold: 4.5
    base64_detection_threshold: 0.7
    data_exfiltration_threshold_mb_per_hour: 100
    beaconing_detection_threshold: 0.8
    txt_record_size_threshold: 512
    monitor_dns_over_https: true
    monitor_dns_over_tls: true
    learning_period_hours: 24
    suspicious_domain_patterns:
    - .*\.onion$
    - .*[0-9]{10,}.*
    - .*[a-fA-F0-9]{32,}.*
    - .*[A-Za-z0-9+/]{20,}=*.*
    - .*\.tk$
    - .*\.ml$
    - .*\.ga$
    - .*\.cf$
    - .*dyndns\..*
    - .*ddns\..*
    - .*ngrok\..*
    known_malicious_domains: []
    known_c2_domains: []
    dns_over_https_providers:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    alert_frequency_limits:
      suspicious_domain:
        max_alerts_per_hour: 10
        cooldown_multiplier: 0.3
      dns_tunneling:
        max_alerts_per_hour: 5
        cooldown_multiplier: 0.5
      high_volume_dns:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.7
  registry_monitor:
    enabled: false
    watched_keys:
    - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    - HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
deduplication:
  # Phase 1: Content-based deduplication
  exact_duplicate_window_secs: 300   # 5 minutes - more aggressive for rapid duplicates
  security_critical_bypass: true
  
  # Phase 2: Burst detection
  burst_threshold: 3                 # Even more aggressive
  burst_window_secs: 10              # Much shorter window - 10 seconds
  burst_summary_interval: 10         # More frequent summaries
  
  # Phase 3: Rate limiting by event type
  file_event_rate_per_minute: 2      # Even tighter rate limiting for file events
  process_event_rate_per_minute: 10
  network_event_rate_per_minute: 20
  security_alert_rate_per_hour: 5
  
  # Phase 2 Enhancements: Pattern-based deduplication
  microsecond_deduplication_window_ms: 50   # 50ms for rapid duplicates - more aggressive
  enable_subsecond_deduplication: true      # Enable sub-second duplicate detection
  rapid_duplicate_threshold: 2              # 2 identical events within microsecond window
  
  # Enhanced content similarity detection
  enable_content_similarity_detection: true # Detect near-identical content
  content_similarity_threshold: 0.95        # 95% similarity threshold
  similarity_window_secs: 60                # 1 minute window for similarity detection
  
  # Adaptive rate limiting based on behavior patterns  
  enable_adaptive_rate_limiting: true       # Adjust rates based on patterns
  noise_pattern_detection_window: 300       # 5 minutes to detect noise patterns
  noise_threshold_multiplier: 2.0           # Reduce rate by half when noise detected
  
  # Memory management
  max_hash_cache_size: 10000
  max_burst_states: 1000
  cleanup_interval_secs: 300
  max_microsecond_cache_size: 5000          # Sub-second deduplication cache
  max_similarity_cache_size: 3000           # Content similarity cache
storage:
  local_storage:
    enabled: true
    data_directory: ./data
    compress_events: true
  retention_days: 30
  max_storage_size_gb: 10
network:
  enabled: false
  server_url: null
  api_key: null
  batch_upload_interval_s: 300
  max_retries: 3
  timeout_s: 30
  use_tls: true
  verify_certificates: true
logging:
  level: info
  file_path: ./logs/edr-agent.log
  max_file_size_mb: 100
  max_files: 10
