agent:
  agent_id: null
  hostname: null
  collection_interval_ms: 5000
  max_events_per_batch: 1000
  max_memory_usage_mb: 512
collectors:
  process_monitor:
    enabled: true
    scan_interval_ms: 1000
    track_child_processes: true
    collect_command_line: true
    collect_environment: false
  file_monitor:
    enabled: true
    watched_paths:
    - /
    - C:\
    ignored_extensions:
    - .tmp
    - .log
    - .cache
    max_file_size_mb: 100
    calculate_hashes: true
  network_monitor:
    enabled: true
    monitor_connections: true
    monitor_dns: true
    capture_packets: false
    max_packet_size: 1500
  registry_monitor:
    enabled: false
    watched_keys:
    - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    - HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
detectors:
  behavioral:
    enabled: true
    scan_interval_ms: 2000
    alert_threshold: 0.6
    prevention_threshold: 0.8
    track_api_calls: true
    monitor_memory_operations: true
    monitor_thread_operations: true
    cross_platform_detection: true
    system_process_contexts: {}
    alert_frequency_limits: {}
    path_context_rules: {}
    network_behavior_rules: {}
    time_based_risk_adjustment:
      business_hours_multiplier: 0.0
      after_hours_multiplier: 0.0
      weekend_multiplier: 0.0
      business_hours_start: 0
      business_hours_end: 0
  dns_anomaly:
    enabled: true
    max_queries_per_minute: 100
    max_queries_per_hour: 1000
    max_unique_domains_per_hour: 500
    entropy_threshold: 4.5
    base64_detection_threshold: 0.7
    data_exfiltration_threshold_mb_per_hour: 100
    beaconing_detection_threshold: 0.8
    txt_record_size_threshold: 512
    monitor_dns_over_https: true
    monitor_dns_over_tls: true
    learning_period_hours: 24
    suspicious_domain_patterns:
    - .*\.onion$
    - .*[0-9]{10,}.*
    - .*[a-fA-F0-9]{32,}.*
    - .*[A-Za-z0-9+/]{20,}=*.*
    - .*\.tk$
    - .*\.ml$
    - .*\.ga$
    - .*\.cf$
    - .*dyndns\..*
    - .*ddns\..*
    - .*ngrok\..*
    known_malicious_domains: []
    known_c2_domains: []
    dns_over_https_providers:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    alert_frequency_limits:
      suspicious_domain:
        max_alerts_per_hour: 10
        cooldown_multiplier: 0.3
      dns_tunneling:
        max_alerts_per_hour: 5
        cooldown_multiplier: 0.5
      high_volume_dns:
        max_alerts_per_hour: 3
        cooldown_multiplier: 0.7
  registry_monitor:
    enabled: false
    watched_keys:
    - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    - HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
deduplication:
  # Phase 1: Content-based deduplication
  exact_duplicate_window_secs: 1800  # 30 minutes (Phase 1 optimization)
  security_critical_bypass: true
  
  # Phase 2: Burst detection
  burst_threshold: 5                 # More aggressive (Phase 1 optimization)
  burst_window_secs: 30              # Shorter window (Phase 1 optimization)
  burst_summary_interval: 25         # More frequent summaries (Phase 1 optimization)
  
  # Phase 3: Rate limiting by event type
  file_event_rate_per_minute: 3      # Tighter rate limiting (Phase 1 optimization)
  process_event_rate_per_minute: 10
  network_event_rate_per_minute: 20
  security_alert_rate_per_hour: 5
  
  # Phase 2 Enhancements: Pattern-based deduplication
  microsecond_deduplication_window_ms: 100  # 100ms for rapid duplicates
  enable_subsecond_deduplication: true      # Enable sub-second duplicate detection
  rapid_duplicate_threshold: 3              # 3 identical events within microsecond window
  
  # Enhanced content similarity detection
  enable_content_similarity_detection: true # Detect near-identical content
  content_similarity_threshold: 0.95        # 95% similarity threshold
  similarity_window_secs: 60                # 1 minute window for similarity detection
  
  # Adaptive rate limiting based on behavior patterns  
  enable_adaptive_rate_limiting: true       # Adjust rates based on patterns
  noise_pattern_detection_window: 300       # 5 minutes to detect noise patterns
  noise_threshold_multiplier: 2.0           # Reduce rate by half when noise detected
  
  # Memory management
  max_hash_cache_size: 10000
  max_burst_states: 1000
  cleanup_interval_secs: 300
  max_microsecond_cache_size: 5000          # Sub-second deduplication cache
  max_similarity_cache_size: 3000           # Content similarity cache
storage:
  local_storage:
    enabled: true
    data_directory: ./data
    compress_events: true
  retention_days: 30
  max_storage_size_gb: 10
network:
  enabled: false
  server_url: null
  api_key: null
  batch_upload_interval_s: 300
  max_retries: 3
  timeout_s: 30
  use_tls: true
  verify_certificates: true
logging:
  level: info
  file_path: ./logs/edr-agent.log
  max_file_size_mb: 100
  max_files: 10
